config/routes.rb
Rails.application.routes.draw do
  get 'photos' => 'photo#index'
  get 'photo_show' => 'photo/show'
  root "photo#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :comments,
            dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = @photo.comments.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoFliker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-faded" style="border-radius: 0; margin-bottom: 30px">
     <%= link_to "Photo Flicker", root_path, class: 'navbar-brand' %>
     <ul class="nav navbar-nav">
       <li class="nav-item active">
         <%= link_to "Timeline", photos_path, class: 'nav-link' %>
       </li>
     </ul>
   </nav>
   <div class="container">
     <%= yield %>
   </div>
  </body>
</html>

app/views/photo/_comment.html.erb
<div class="card-footer text-muted">

</div>

app/views/photo/_photo.html.erb
<% @photos.each do |photo| %>
    <div class="card">
      <div class="card-header">
        <div class="avatar">
          <%= image_tag Faker::Avatar.image(photo.username, '32x32') %>
          <%= photo.username %>
          <span class="timestamp pull-xs-right"><%= time_ago_in_words photo.created_at %></span>
        </div>

      </div>
      <img class="card-img-center" src=<%= photo.url %> alt="<%= photo.username %>">

      <div class="card-block">
        <%= render 'comment' %><br>
        <a href="#" class="btn btn-primary"><%= photo.likes_count %>&nbspLikes</a>
      </div>
    </div>
<% end %>
w

app/views/photo/index.html.erb
<%= render 'photo' %>

app/views/photo/show.html.erb
<h1>Photo#show</h1>
<p>Find me in app/views/photo/show.html.erb</p>